# Generated by Django 5.2.9 on 2026-02-15 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dawah", "0001_initial"),
        ("quiz", "0002_remove_course_students_enrollment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="related_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.course",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="related_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dawah.event",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="time_limit",
            field=models.PositiveSmallIntegerField(
                help_text="Time limit in minutes", null=True
            ),
        ),
    ]
